INSERT INTO Genre (name) VALUES
("Drama"),
("Crime"),
("Action"),
("Sci-Fi"),
("Fantasy"),
("Thriller"),
("War"),
("Romance"),
("Adventure"),
("Comedy"),
("Horror"),
("Mystery");

INSERT INTO Movie VALUES
(DEFAULT, "The Shawshank Redemption", 1),
(DEFAULT, "Pulp Fiction", 2),
(DEFAULT, "The Godfather", 2),
(DEFAULT, "Forrest Gump", 1),
(DEFAULT, "The Dark Knight", 3),
(DEFAULT, "Inception", 4),
(DEFAULT, "Goodfellas", 2),
(DEFAULT, "Fight Club", 1),
(DEFAULT, "The Matrix", 4),
(DEFAULT, "The Lord of the Rings: The Fellowship of the Ring", 5),
(DEFAULT, "Schindler's List", 1),
(DEFAULT, "The Silence of the Lambs", 6),
(DEFAULT, "Gladiator", 3),
(DEFAULT, "The Avengers", 3),
(DEFAULT, "Saving Private Ryan", 7),
(DEFAULT, "The Departed", 2),
(DEFAULT, "Avatar", 4),
(DEFAULT, "The Titanic", 8),
(DEFAULT, "Jurassic Park", 9),
(DEFAULT, "The Revenant", 9),
(DEFAULT, "The Great Gatsby", 1),
(DEFAULT, "The Social Network", 1),
(DEFAULT, "The Shawshank Redemption", 1),
(DEFAULT, "The Grand Budapest Hotel", 10),
(DEFAULT, "The Green Mile", 1),
(DEFAULT, "Casablanca", 8),
(DEFAULT, "Blade Runner", 4),
(DEFAULT, "The Exorcist", 11),
(DEFAULT, "The Godfather: Part II", 2),
(DEFAULT, "The Departed", 2),
(DEFAULT, "E.T. the Extra-Terrestrial", 4),
(DEFAULT, "Forrest Gump", 1),
(DEFAULT, "The Lord of the Rings: The Two Towers", 5),
(DEFAULT, "Gladiator", 3),
(DEFAULT, "The Dark Knight Rises", 3),
(DEFAULT, "The Shining", 11),
(DEFAULT, "American Beauty", 1),
(DEFAULT, "Inception", 4),
(DEFAULT, "Schindler's List", 1),
(DEFAULT, "The Matrix", 4),
(DEFAULT, "Braveheart", 7),
(DEFAULT, "Jurassic Park", 9),
(DEFAULT, "The Green Mile", 1),
(DEFAULT, "The Revenant", 9),
(DEFAULT, "The Great Gatsby", 1),
(DEFAULT, "The Social Network", 1),
(DEFAULT, "The Silence of the Lambs", 6),
(DEFAULT, "American History X", 1),
(DEFAULT, "Goodfellas", 2),
(DEFAULT, "Memento", 12);
