DROP DATABASE IF EXISTS movie_db;

CREATE DATABASE movie_db;

USE movie_db;

CREATE TABLE Genre (
id INT PRIMARY KEY AUTO_INCREMENT,
name TEXT NOT NULL
);

CREATE TABLE User (
id INT PRIMARY KEY AUTO_INCREMENT,
nickname TEXT NOT NULL
);

CREATE TABLE Movie (
id INT PRIMARY KEY AUTO_INCREMENT,
name TEXT NOT NULL,
genre_id INT NOT NULL,

FOREIGN KEY (genre_id) 
REFERENCES Genre (id) 
ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE Watched (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
movie_id INT NOT NULL,

FOREIGN KEY (user_id) 
REFERENCES User (id) 
ON DELETE RESTRICT ON UPDATE RESTRICT,

FOREIGN KEY (movie_id) 
REFERENCES Movie (id) 
ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE Preference (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
genre_id INT NOT NULL,

FOREIGN KEY (user_id) 
REFERENCES User (id) 
ON DELETE RESTRICT ON UPDATE RESTRICT,

FOREIGN KEY (genre_id) 
REFERENCES Genre (id) 
ON DELETE RESTRICT ON UPDATE RESTRICT
);
